# Databricks App Configuration
command:
  - "bash"
  - "-c"
  - "pip3 install -r backend/requirements.txt && cd backend && ../.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${DATABRICKS_APP_PORT:-8000}"

env:
  - name: DATABRICKS_CATALOG
    value: "serverless_dxukih_catalog"
  - name: DATABRICKS_SCHEMA
    value: "mirion"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "387bcda0f2ece20c"
